FROM python:3.7
ADD News_Analysis.py /
RUN pip install requests
RUN pip install pandas
RUN pip install numpy
RUN pip install  pprint
RUN pip install  bs4
RUN pip install nltk
RUN pip install  gensim
RUN pip install  matplotlib
RUN pip install  spacy

CMD [ "python", "./News_Analysis.py" ]